[vpn_nodes]
157.230.93.112 ansible_user=root ansible_password=MadMan12321@##**s
167.71.199.96   ansible_user=root ansible_password=MadMan12321@##**s

[vpn_nodes:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
wireguard_port=51820
